# 🏥 CariSurg MedTech Pathways — Week 0, Tutorial 1
## Python for Basic Data Exploration & Cleaning
**Mercer General Hospital | Clinical AI & Innovation Unit**

---
> **Scenario:** You have just joined the Clinical AI & Innovation Unit at Mercer General Hospital.
> Dr. De Freitas has asked you to get your tools in place and run a first look at a sample triage dataset.
> Today we focus on getting set up and tackling Day 1's challenge: cleaning the Gender column.

---
### What we will cover today
1. Google Colab environment walkthrough
2. Python basics — variables, data types, lists, loops, conditionals, functions
3. Importing libraries and loading a CSV
4. Cleaning the `Gender` column (Day 1 challenge)

**Day 1 Submission:** A Jupyter notebook showing your cleaned `Gender` column — pushed to your `carisurg-portfolio` GitHub repo.

## 1. Google Colab Environment

**[TUTOR NOTE — live demo, ~5 min]**
- Show the Colab interface: toolbar, code cells vs markdown cells, runtime menu
- Run a cell: `Shift + Enter`
- Show how to mount Google Drive (run the cell below)
- Confirm Python version

In [2]:
# Mount your Google Drive so files are accessible from Colab
from google.colab import drive
drive.mount('/content/drive')
print("Drive mounted successfully!")

Mounted at /content/drive
Drive mounted successfully!

In [3]:
# Always confirm your Python version first
import sys
print(f"Python version: {sys.version}")
# We need 3.10 or higher for this programme

Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

## 2. Python Basics

**[TUTOR NOTE — live coding, ~20 min]**
Run each block, pause, ask students to predict the output before you run it.
The goal is familiarity — not memorisation.

### 2.1 Variables and Data Types

In [4]:
# Variables store values. Python figures out the type automatically.
patient_id    = 42          # integer
patient_name  = "Maria"     # string
heart_rate    = 88.5        # float
is_critical   = True        # boolean

print(f"Patient:    {patient_name}")
print(f"Heart rate: {heart_rate} bpm")
print(f"Critical:   {is_critical}")
print(f"Type of heart_rate: {type(heart_rate)}")

Patient:    Maria
Heart rate: 88.5 bpm
Critical:   True
Type of heart_rate: <class 'float'>

### 2.2 Lists

In [5]:
# A list holds multiple values in order
vital_signs = ["pulse", "temperature", "SBP", "DBP", "RR", "FiO2", "GCS"]

print("All vitals:", vital_signs)
print("First vital:", vital_signs[0])      # indexing starts at 0
print("Last vital:", vital_signs[-1])      # -1 gets the last item
print("Number of vitals:", len(vital_signs))

All vitals: ['pulse', 'temperature', 'SBP', 'DBP', 'RR', 'FiO2', 'GCS']
First vital: pulse
Last vital: GCS
Number of vitals: 7

### 2.3 Loops

In [6]:
# A for loop runs a block of code once for each item in a list
for vital in vital_signs:
    print(f"  - {vital}")

  - pulse
  - temperature
  - SBP
  - DBP
  - RR
  - FiO2
  - GCS

### 2.4 Conditional Logic (if / elif / else)

In [7]:
# Conditionals let code make decisions
def classify_pulse(bpm):
    if bpm < 60:
        return "Bradycardia (too slow)"
    elif bpm > 100:
        return "Tachycardia (too fast)"
    else:
        return "Normal"

# Test it
test_pulses = [45, 78, 130]
for p in test_pulses:
    print(f"  Pulse {p} bpm -> {classify_pulse(p)}")

  Pulse 45 bpm -> Bradycardia (too slow)
  Pulse 78 bpm -> Normal
  Pulse 130 bpm -> Tachycardia (too fast)

### 2.5 Functions

In [8]:
# Functions package reusable code
def greet_trainee(name, unit="Clinical AI & Innovation Unit"):
    message = f"Welcome to Mercer General, {name}. You are now part of the {unit}."
    return message

print(greet_trainee("Maria")) # If the unit is not specified it is reverts to the default variable in its definition.
print(greet_trainee("James", "Emergency Department"))

Welcome to Mercer General, Maria. You are now part of the Clinical AI & Innovation Unit.
Welcome to Mercer General, James. You are now part of the Emergency Department.

## 3. Importing Libraries and Loading the Dataset

**[TUTOR NOTE — live demo, ~10 min]**
Show students where to upload the CSV in Colab (Files panel on the left).
The path below assumes the file is uploaded directly to Colab's session storage.
Students who use Drive can adjust the path.

In [9]:
# The three libraries we use most in this programme
import pandas as pd          # data manipulation
import numpy as np           # numerical operations
import matplotlib.pyplot as plt  # plotting

print("Libraries imported successfully!")

Libraries imported successfully!

This will vary depending on whether you are using Python locally or through Google Collab.

In [11]:
# ── TUTOR: adjust this path if the file is in Drive ──────────
# Please update this FILE_PATH with the correct path to your CSV file
FILE_PATH = '/content/EmergencyTriageDataset_Reduced_Dirty.csv'

df_raw = pd.read_csv(FILE_PATH)
print(f"Dataset loaded: {df_raw.shape[0]} rows x {df_raw.shape[1]} columns")
print(f"Columns: {list(df_raw.columns)}")

Dataset loaded: 2205 rows x 11 columns
Columns: ['ID', 'Age', 'Gender', 'GCS', 'SBP', 'DBP', 'MAP', 'pulse', 'Temp', 'RR', 'Fio2']

### Locate your CSV file

The `FileNotFoundError` means Python couldn't find your CSV file at the path `/content/drive/MyDrive/ColabNotebooks/CariSurg_Triage_Test/EmergencyTriageDataset_Reduced_Dirty.csv`.

Here are some common locations where your file might be. Run the cells below to check these locations, and if you find your file, copy its full path and update the `FILE_PATH` variable in the previous code cell.

In [12]:
# List files in the root of your Google Drive
print('Listing files in /content/drive/MyDrive/')
!ls -F '/content/drive/MyDrive/'

# List files in the 'Colab Notebooks' folder (a common location for Colab files)
print('\nListing files in /content/drive/MyDrive/Colab Notebooks/')
!ls -F '/content/drive/MyDrive/Colab Notebooks/'

# List files in the folder specified in your original path, if it exists
print('\nListing files in /content/drive/MyDrive/ColabNotebooks/CariSurg_Triage_Test/')
!ls -F '/content/drive/MyDrive/ColabNotebooks/CariSurg_Triage_Test/'

Listing files in /content/drive/MyDrive/
 Aggregation.pdf     'Colab Notebooks'/      passport.jpeg
 Azaria_DaSilva.pdf   Crud.pdf		     report.pdf
 Classroom/	     'Getting started.pdf'   Status/

Listing files in /content/drive/MyDrive/Colab Notebooks/
'Copy of Week0_Tutorial1_EnvSetup_and_Cleaning_Gender.ipynb'

Listing files in /content/drive/MyDrive/ColabNotebooks/CariSurg_Triage_Test/
ls: cannot access '/content/drive/MyDrive/ColabNotebooks/CariSurg_Triage_Test/': No such file or directory

In [13]:
# Always look at the first few rows immediately after loading
df_raw.head(10)

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0
5   6   42    Male  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6   7   75  Female  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7   8   25    Male  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8   9   67       0  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9  11   82  Female  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0

In [14]:
# What data types does pandas think each column is?
print(df_raw.dtypes)

ID          int64
Age         int64
Gender     object
GCS        object
SBP        object
DBP       float64
MAP       float64
pulse      object
Temp       object
RR        float64
Fio2      float64
dtype: object

**[TUTOR NOTE — pause here]**
Point out that `Gender`, `GCS`, `SBP`, and `pulse` are `object` (string) type — even though they should be numbers.
This is the first clue that the data is dirty. Ask students: *why might this happen in a real hospital dataset?*

## 4. Day 1 Challenge — Cleaning the Gender Column

**[TUTOR NOTE — this is the core of Tutorial 1, ~25 min]**

**First, explore before cleaning.** Never clean data you have not looked at.
Walk through each step below and explain the reasoning out loud.

In [15]:
# Step 1: What values are actually in the Gender column?
print("Unique values in Gender:")
print(df_raw['Gender'].unique())
print(f"\nTotal unique values: {df_raw['Gender'].nunique()}")

Unique values in Gender:
['0' 'Male' 'Female' 'FEMALE' '1' 'MALE']

Total unique values: 6

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

**[TUTOR NOTE — discussion pause]**
You should see six variants: `0`, `1`, `Male`, `MALE`, `Female`, `FEMALE`.

Ask the class: *Should we represent Gender as M/F or 1/0? What are the trade-offs?*

Key points to draw out:
- `1/0` (integer encoding) is easier for models to process later
- `M/F` is more readable for humans
- The programme uses `1 = Male, 0 = Female` — consistent with the Harvard dataset
- This is a *design decision* — what matters is that you document it

In [17]:
# Step 2: Count how many of each value we have
print("Gender value counts:")
print(df_raw['Gender'].value_counts())

Gender value counts:
Gender
1         422
MALE      379
Male      375
FEMALE    366
Female    340
0         323
Name: count, dtype: int64

In [18]:
# Step 3: Build the mapping — every variant maps to 1 or 0
gender_map = {
    'male':   1,
    'female': 0,
    'non-binary': 2,
    'nonbinary': 2,
    'non_binary': 2,
    'nb': 2,
    '1':      1,
    '0':      0
}

# Step 4: Apply the mapping to create a new, clean column
# It is best practice to make changes to a new column rather than editing an
# exising one.
df_raw['Gender_Clean'] = df_raw['Gender'].astype(str).str.lower().str.strip().map(gender_map)

# Step 5: Verify — check what we have now
print("After cleaning:")
print(df_raw['Gender_Clean'].value_counts())
print(f"\nAny NaN values? {df_raw['Gender_Clean'].isnull().sum()}")

After cleaning:
Gender_Clean
1    1176
0    1029
Name: count, dtype: int64

Any NaN values? 0

In [19]:
# Step 6: Drop the original dirty column now that we have a clean one
df_raw = df_raw.drop(columns=['Gender'])
df_raw = df_raw.rename(columns={'Gender_Clean': 'Gender'})

# Confirm the result
# 0 = Female, 1 = Male, 2 = Non-Binary
print("Column 'Gender' after cleaning:")
print(df_raw['Gender'].value_counts())
print(f"Data type: {df_raw['Gender'].dtype}")
df_raw.head()

Column 'Gender' after cleaning:
Gender
1    1176
0    1029
Name: count, dtype: int64
Data type: int64

   ID  Age   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2  Gender
0   1   34  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0       0
1   2   20  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0       1
2   3   77  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0       0
3   4   23   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0       0
4   5   86  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0       0

**[TUTOR NOTE — common errors to watch for]**

1. **Using `.replace()` instead of `.map()`** — both work, but `.map()` is safer for column-wide remapping because any unmatched value becomes `NaN` (a useful warning signal).
2. **Forgetting `.inplace=True` or reassignment** — a very common beginner mistake. Always show students `df['col'] = df['col'].something()` vs `df['col'].something(inplace=True)`.
3. **Case sensitivity** — `'male'` and `'Male'` are different strings. Show them `str.lower()` as an alternative approach if the mapping gets unwieldy.

**Alternative approach (bonus, if time permits):**

In [20]:
# Alternative: normalise to lowercase first, then map
# This handles any future casing variants automatically
gender_map_v2 = {'male': 1, 'female': 0, 'non-binalry':2, 'non_binary':2, 'nonbinary':2, 'nb':2, '1': 1, '0': 0}

# Reset and try the alternative approach on a copy
df_test = pd.read_csv(FILE_PATH)
df_test['Gender_v2'] = df_test['Gender'].astype(str).str.lower().str.strip().map(gender_map_v2)
print(df_test['Gender_v2'].value_counts())
print(f"NaNs: {df_test['Gender_v2'].isnull().sum()}")

Gender_v2
1    1176
0    1029
Name: count, dtype: int64
NaNs: 0

## 5. Submission Reminder

**Day 1 Deliverable:**
1. Save this notebook with your cleaned `Gender` column
2. Push it to your `carisurg-portfolio` GitHub repo
3. Post a screenshot in the `#cohort-2026` Discord channel

**Tomorrow (Day 2):** You will be assigned a different column to clean in your breakout group.
Come prepared — re-read the dataset column descriptions before the session.

---
### Quick Reference Card

| Concept | Code |
|---------|------|
| Load a CSV | `pd.read_csv('file.csv')` |
| See unique values | `df['col'].unique()` |
| Count each value | `df['col'].value_counts()` |
| Remap values | `df['col'].map({'old': 'new'})` |
| Drop a column | `df.drop(columns=['col'])` |
| Rename a column | `df.rename(columns={'old': 'new'})` |

## 6. Closing Q&A

**[TUTOR NOTE — suggested questions to prompt discussion]**
- "If a new patient record arrived with `Gender = 'F'`, what would our cleaning pipeline do? Is that a problem?"
- "We chose `1 = Male, 0 = Female`. Who made that decision, and should it be documented somewhere?"
- "What if a patient's gender is non-binary? How would you handle that in a real clinical system?"

These questions have no single right answer — the goal is to get students thinking about *design choices*, not just code.